# Generated by Django 2.1.1 on 2018-10-03 19:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Article Title', max_length=100)),
                ('author', models.CharField(help_text='Article Author', max_length=50)),
                ('pub_date', models.DateTimeField(default=datetime.datetime(2018, 10, 3, 19, 3, 43, 758841))),
                ('body', models.TextField()),
            ],
        ),
    ]
